namespace: f5networks
name: f5_beacon
version: 0.5.2-beta
readme: README.md
authors:
  - Wojciech Wypior (@wojtek0806)
description: Collection to manage F5 Beacon objects
license: GPL-3.0-only
tags:
  - f5
  - cloud
  - beacon
dependencies: {}
repository: https://github.com/F5Networks/f5-beacon
documentation: https://github.com/F5Networks/f5-beacon
homepage: https://github.com/F5Networks/f5-beacon
issues: https://github.com/F5Networks/f5-beacon/issues
